"""Instruction sheet for the JSON number routine (GetJsonNumber: text -> TVarData, returns the cursor or
nil): the string scanner's window and rows, the JSON grammar (no spaces/plus, no leading zero, a
digit after the dot and after the exponent sign, a dot after the number is invalid), the type by
value (varInteger <= 999999999, varInt64, else varDouble), the same converter arithmetic as the
string routine (bits = libfinal), nil for doubles when not allowed and for range errors. Sizes as
Delphi encodes them; the generic tools solve.py / emit.py / layout.py place, write and check it."""
from pathlib import Path
NAME = 'json'
E18 = 'mov r10, 1000000000000000000'
SUB = ('sub eax, 48 | sub al, 48', [3, 2])
CMP9 = ('cmp eax, 9 | cmp al, 9', [3, 2])
INC = ('inc rcx | add rcx, 1', [3, 4])
LOAD = ('movzx eax, byte ptr [rcx]', 3)
# r11 flag bits: 1 AllowDouble, 2 negative, 4 negative exponent, 8 digits discarded (beyond the 19th)
hot = [
 ('movzx r11d, r8b', 4), ('test rcx, rcx', 3), ('jz @nilHot', 2), ('mov eax, ecx', 2), ('and eax, 4095', 5), ('or eax, [rip + NOSIMD]', 6),
 ('cmp byte ptr [rcx], 45', 3), ('je @negative', 6), ('lea r8, [rip + NumberSimdData]', 7),
 ('@unsigned:', 0), ('cmp eax, 4079', 5), ('ja @bytes', 6),
 ('movdqu xmm0, [rcx]', 4), ('movdqa xmm1, xmm0', 4), ('paddb xmm1, [bias]', 8), ('pcmpgtb xmm1, [threshold]', 8),
 ('pmovmskb r10d, xmm1', 5), ('not r10d', 3), ('tzcnt eax, r10d', 5),
 ('lea r9d, [rax - 1]', 4), ('cmp r9d, 14', 4), ('ja @window0or16', 6),
 ('movzx r9d, word ptr [rcx]', 4), ('sub r9d, 12336', 7), ('ror r9d, 8', 4), ('cmp r9d, 9', 4), ('jbe @nilHot', 2),
 ('movzx r9d, byte ptr [rcx + rax]', 5), ('cmp r9d, 46', 4), ('je @fraction', 2),
 # ---- integer, <= 8 digits: dword 0 of the product is M; the cursor = P + p; varInteger
 ('psubb xmm0, [r8 + 32]', 6), ('cmp eax, 8', 3), ('ja @integerWideRows', 2),
 ('lea r10d, [rax + rax]', 4), ('pshufb xmm0, [r8 + r10 * 8 + 576]', 11), ('pmaddubsw xmm0, [r8 + 48]', 7), ('pmaddwd xmm0, [r8 + 64]', 6),
 ('packssdw xmm0, xmm0', 4), ('pmaddwd xmm0, [r8 + 80]', 6),
 ('movd r8d, xmm0', 5), ('add rax, rcx', 3), ('or r9d, 32', 4), ('cmp r9d, 101', 4), ('je @integerShortExponent', 2),
 ('test r11b, 2', 4), ('jnz @negateShort', 2),
 ('mov qword ptr [rdx + 8], r8', 4), ('mov dword ptr [rdx], 3', 6), ('ret', 1),
 ('@negateShort:', 0), ('neg r8', 3), ('mov qword ptr [rdx + 8], r8', 4), ('mov dword ptr [rdx], 3', 6), ('ret', 1),
 ('@nilHot:', 0), ('xor eax, eax', 2), ('ret', 1),
 ('@integerShortExponent:', 0), ('cvtsi2sd xmm0, r8', 5), ('lea rcx, [rax + 1]', 4), ('xor r9d, r9d', 3), ('jmp @fastExponent', 5),
 # ---- integer, 9..15 digits: dword 0 = H, dword 1 = L, M = H * 10^8 + L; the type by value
 ('@integerWideRows:', 0), ('lea r10d, [rax + rax]', 4), ('pshufb xmm0, [r8 + r10 * 8 + 96]', 8), ('pmaddubsw xmm0, [r8 + 48]', 7), ('pmaddwd xmm0, [r8 + 64]', 6),
 ('packssdw xmm0, xmm0', 4), ('pmaddwd xmm0, [r8 + 80]', 6),
 ('movq r8, xmm0', 5), ('mov r10d, r8d', 3), ('shr r8, 32', 4), ('imul r10, r10, 100000000', 7), ('add r8, r10', 3),
 ('add rax, rcx', 3), ('or r9d, 32', 4), ('cmp r9d, 101', 4), ('je @integerExponent', 2),
 ('mov r10d, 3', 6), ('mov r9d, 20', 6), ('cmp r8, 999999999', 7), ('cmova r10d, r9d', 4),
 ('test r11b, 2', 4), ('jnz @negateWide', 2),
 ('mov qword ptr [rdx + 8], r8', 4), ('mov dword ptr [rdx], r10d', 3), ('ret', 1),
 ('@negateWide:', 0), ('neg r8', 3), ('mov qword ptr [rdx + 8], r8', 4), ('mov dword ptr [rdx], r10d', 3), ('ret', 1),
 ('@integerExponent:', 0), ('cvtsi2sd xmm0, r8', 5), ('lea rcx, [rax + 1]', 4), ('xor r9d, r9d', 3), ('jmp @fastExponent', 5),
 # ---- fraction: p integer digits, the dot, f fraction digits up to lane 15 (n = first non-digit after them)
 ('@fraction:', 0), ('btr r10d, eax', 4), ('tzcnt r10d, r10d', 5), ('psubb xmm0, [r8 + 32]', 6),
 ('lea r9d, [rax + rax]', 4), ('pshufb xmm0, [r8 + r9 * 8 + 336]', 11), ('lea r9d, [r10 + r10 - 2]', 5),
 ('cmp r10d, 9', 4), ('ja @fractionWideRows', 2),
 ('pshufb xmm0, [r8 + r9 * 8 + 576]', 11), ('pmaddubsw xmm0, [r8 + 48]', 7), ('pmaddwd xmm0, [r8 + 64]', 6), ('packssdw xmm0, xmm0', 4), ('pmaddwd xmm0, [r8 + 80]', 6),
 ('sub r10d, eax', 3), ('add rcx, rax', 3), ('cmp r10d, 1', 4), ('je @nilHot', 2), ('add rcx, r10', 3),
 ('movzx eax, byte ptr [rcx]', 3), ('cmp eax, 46', 3), ('je @nilHot', 2), ('or eax, 32', 3), ('cmp eax, 101', 3), ('je @fractionShortExponent', 2),
 ('cvtdq2pd xmm0, xmm0', 4), ('divsd xmm0, [r8 + r10 * 8 + 712]', 10),
 ('@storeDouble:', 0), ('test r11b, 1', 4), ('jz @nilHot', 2), ('movsd qword ptr [rdx + 8], xmm0', 5), ('test r11b, 2', 4), ('jnz @negateDouble', 2),
 ('mov dword ptr [rdx], 5', 6), ('mov rax, rcx', 3), ('ret', 1),
 ('@negateDouble:', 0), ('pxor xmm1, xmm1', 4), ('cmpneqsd xmm1, xmm0', 5), ('andpd xmm1, [sign]', 8), ('xorpd xmm0, xmm1', 4), ('movsd qword ptr [rdx + 8], xmm0', 5), ('mov dword ptr [rdx], 5', 6), ('mov rax, rcx', 3), ('ret', 1),
 ('@fractionShortExponent:', 0), ('cvtdq2pd xmm0, xmm0', 4), ('mov r9d, 1', 6), ('sub r9, r10', 3), ('inc rcx', 3), ('jmp @fastExponent', 5),
 ('@fractionWideRows:', 0), ('cmp r10d, 16', 4), ('je @windowFraction', 6),
 ('pshufb xmm0, [r8 + r9 * 8 + 96]', 8), ('pmaddubsw xmm0, [r8 + 48]', 7), ('pmaddwd xmm0, [r8 + 64]', 6), ('packssdw xmm0, xmm0', 4), ('pmaddwd xmm0, [r8 + 80]', 6),
 ('sub r10d, eax', 3), ('add rcx, rax', 3), ('cmp r10d, 1', 4), ('je @nilHot', 2), ('add rcx, r10', 3),
 ('movzx eax, byte ptr [rcx]', 3), ('cmp eax, 46', 3), ('je @nilHot', 2), ('or eax, 32', 3), ('cmp eax, 101', 3), ('je @fractionExponent', 2),
 ('cvtdq2pd xmm0, xmm0', 4), ('movhlps xmm1, xmm0', 3), ('mulsd xmm0, [r8 + 104]', 6), ('addsd xmm0, xmm1', 4),
 ('divsd xmm0, [r8 + r10 * 8 + 712]', 10),
 ('test r11b, 1', 4), ('jz @nilHot', 2), ('movsd qword ptr [rdx + 8], xmm0', 5), ('test r11b, 2', 4), ('jnz @negateDouble', 2),
 ('mov dword ptr [rdx], 5', 6), ('mov rax, rcx', 3), ('ret', 1),
 ('@fractionExponent:', 0), ('cvtdq2pd xmm0, xmm0', 4), ('movhlps xmm1, xmm0', 3), ('mulsd xmm0, [r8 + 104]', 6), ('addsd xmm0, xmm1', 4),
 ('mov r9d, 1', 6), ('sub r9, r10', 3), ('inc rcx', 3),
 # ---- the inline exponent: xmm0 = the digits as an exact double, rcx = after the e, r9 = -f; up to three
 # exponent digits (rcx + r8 = the current byte); scale 0 -> an integer of the digits; |scale| <= 22 -> the
 # exact conversion (the same operations as the converter); no digit -> nil; a dot after -> nil
 ('@fastExponent:', 0), ('movzx eax, byte ptr [rcx]', 3), ('xor r8d, r8d', 3), ('cmp eax, 43', 3), ('je @feSkip', 2), ('cmp eax, 45', 3), ('jne @feFirst', 2), ('or r11d, 4', 4),
 ('@feSkip:', 0), ('inc r8d', 3), ('movzx eax, byte ptr [rcx + r8]', 5),
 ('@feFirst:', 0), ('sub eax, 48', 3), ('cmp eax, 9', 3), ('ja @nilHot', 2),
 ('inc r8d', 3), ('movzx r10d, byte ptr [rcx + r8]', 5), ('sub r10d, 48', 4), ('cmp r10d, 9', 4), ('ja @feEnd', 2),
 ('lea eax, [rax + rax * 4]', 3), ('lea eax, [r10 + rax * 2]', 4), ('inc r8d', 3), ('movzx r10d, byte ptr [rcx + r8]', 5), ('sub r10d, 48', 4), ('cmp r10d, 9', 4), ('ja @feEnd', 2),
 ('lea eax, [rax + rax * 4]', 3), ('lea eax, [r10 + rax * 2]', 4), ('inc r8d', 3), ('movzx r10d, byte ptr [rcx + r8]', 5), ('sub r10d, 48', 4), ('cmp r10d, 9', 4), ('jbe @feGeneric', 2),
 ('@feEnd:', 0), ('add rcx, r8', 3), ('cmp r10d, -2', 4), ('je @nilHot', 2), ('movsxd rax, eax', 3), ('test r11b, 4', 4), ('jz @fePlus', 2), ('neg rax', 3),
 ('@fePlus:', 0), ('add r9, rax', 3), ('jnz @feDouble', 2),
 ('cvttsd2si r8, xmm0', 5), ('mov r10d, 3', 6), ('mov r9d, 20', 6), ('cmp r8, 999999999', 7), ('cmova r10d, r9d', 4), ('jmp @typed', 5),
 ('@feDouble:', 0), ('test r11b, 1', 4), ('jz @nilHot', 2), ('lea rax, [r9 + 22]', 4), ('cmp rax, 44', 4), ('ja @feWide', 2),
 ('lea rax, [rip + POW10]', 7), ('test r9, r9', 3), ('js @feDivide', 2), ('mulsd xmm0, [rax + r9 * 8 + 248]', 10),
 ('@feStore:', 0), ('test r11b, 2', 4), ('jnz @feNegate', 2), ('movsd qword ptr [rdx + 8], xmm0', 5), ('mov dword ptr [rdx], 5', 6), ('mov rax, rcx', 3), ('ret', 1),
 ('@feNegate:', 0), ('pxor xmm1, xmm1', 4), ('cmpneqsd xmm1, xmm0', 5), ('andpd xmm1, [sign]', 8), ('xorpd xmm0, xmm1', 4), ('movsd qword ptr [rdx + 8], xmm0', 5), ('mov dword ptr [rdx], 5', 6), ('mov rax, rcx', 3), ('ret', 1),
 ('@feDivide:', 0), ('neg r9', 3), ('divsd xmm0, [rax + r9 * 8 + 248]', 10), ('jmp @feStore', 2),
 ('@feGeneric:', 0), ('cvttsd2si r8, xmm0', 5), ('dec rcx', 3), ('jmp @exponent', 5),
 ('@feWide:', 0), ('cvttsd2si r8, xmm0', 5), ('jmp @double', 5),
 # ---- the minus sign (out of line: positive numbers fall through at the entry)
 ('@negative:', 0), ('inc rcx', 3), ('or r11d, 2', 4), ('mov eax, ecx', 2), ('and eax, 4095', 5), ('or eax, [rip + NOSIMD]', 6), ('lea r8, [rip + NumberSimdData]', 7), ('jmp @unsigned', 5),
]
cold = [
 # ---- 15 digits with the dot, the fraction runs past the window: eax = p, xmm0 = digits (dot removed), r8 = table
 ('@windowFraction:', 0), ('pshufb xmm0, [r8 + 336]', 10), ('pmaddubsw xmm0, [r8 + 48]', 7), ('pmaddwd xmm0, [r8 + 64]', 6), ('packssdw xmm0, xmm0', 4), ('pmaddwd xmm0, [r8 + 80]', 6),
 ('movq r8, xmm0', 5), ('mov r9d, r8d', 3), ('shr r8, 32', 4), ('imul r9, r9, 100000000', 7), ('add r8, r9', 3),
 ('lea r9, [rax - 15]', 4), ('add rcx, 15', 4), ('cmp eax, 15', 3), ('je @dot15', 2),
 ('test r8, r8', 3), ('jz @fractionZeros', 2), (E18, 10), ('jmp @fractionNext', 2),
 ('@dot15:', 0), (E18, 10), ('jmp @dot', 2),
 # ---- the window is full (16 digits) or has no leading digit
 ('@window0or16:', 0), ('test eax, eax', 2), ('jz @nil', 2), ('psubb xmm0, [r8 + 32]', 6), ('cmp byte ptr [rcx], 48', 3), ('je @nil', 2),
 ('pmaddubsw xmm0, [r8 + 48]', 7), ('pmaddwd xmm0, [r8 + 64]', 6), ('packssdw xmm0, xmm0', 4), ('pmaddwd xmm0, [r8 + 80]', 6),
 ('movq r8, xmm0', 5), ('mov eax, r8d', 3), ('shr r8, 32', 4), ('imul rax, rax, 100000000', 7), ('add r8, rax', 3),
 ('add rcx, 15', 4), ('xor r9d, r9d', 3), (E18, 10), ('jmp @integerNext', 2),
 # ---- byte scan from the start (the window would cross the page): rcx = the first byte after an optional -
 ('@bytes:', 0), LOAD, SUB, CMP9, ('ja @nil', 2), ('xor r9d, r9d', 3), (E18, 10), ('mov r8d, eax', 3), ('test eax, eax', 2), ('jnz @integerNext', 2),
 ('movzx eax, byte ptr [rcx + 1]', 4), SUB, CMP9, ('jbe @nil', 2), ('jmp @integerNext', 2),
 # ---- an integer digit beyond the 19 kept: it raises the scale; the number is a double (at most 64, else nil)
 ('@integerDrop:', 0), ('or r11d, 8', 4),
 ('@integerDropLoop:', 0), ('inc r9 | add r9, 1', [3, 4]), ('cmp r9, 64', 4), ('ja @nil', 2), INC, LOAD, SUB, CMP9, ('jbe @integerDropLoop', 2), ('jmp @integerDone', 2),
 # ---- integer digits: rcx = the current digit (eax); exit with rcx = the terminator, al = byte - 48
 ('@integerLoop:', 0), ('cmp r8, r10', 3), ('jae @integerDrop', 2), ('lea r8, [r8 + r8 * 4]', 4), ('lea r8, [rax + r8 * 2]', 4),
 ('@integerNext:', 0), INC, LOAD, SUB, CMP9, ('jbe @integerLoop', 2),
 ('@integerDone:', 0), ('cmp al, 254', 2), ('jne @afterDigits', 2),
 ('@dot:', 0), INC, LOAD, SUB, CMP9, ('ja @nil', 2), ('test r8, r8', 3), ('jnz @fractionLoop', 2),
 # ---- M = 0 so far: the leading zeros of the fraction are capped at 64 (r9 counts them down); beyond: nil
 ('test eax, eax', 2), ('jnz @fractionLoop', 2), ('dec r9', 3),
 ('@fractionZeros:', 0), INC, LOAD, ('sub al, 48', 2), ('jnz @fractionZerosEnd', 2), ('dec r9', 3), ('cmp r9, -64', 4), ('jge @fractionZeros', 2), ('jmp @nil', 2),
 ('@fractionZerosEnd:', 0), (E18, 10), ('cmp al, 9', 2), ('jbe @fractionLoop', 2), ('jmp @afterDigits', 2),
 # ---- not a number
 ('@nil:', 0), ('xor eax, eax', 2), ('ret', 1),
 # ---- fraction digits beyond the 19 kept: skipped (the scale count of this one undone); the number is a double
 ('@fractionDrop:', 0), ('inc r9', 3), ('or r11d, 8', 4), ('mov r10d, 64', 6),
 ('@fractionDropLoop:', 0), INC, LOAD, SUB, CMP9, ('ja @afterDigits', 2), ('dec r10', 3), ('jnz @fractionDropLoop', 2), ('jmp @nil', 2),
 ('@fractionLoop:', 0), ('dec r9 | sub r9, 1', [3, 4]), ('cmp r8, r10', 3), ('jae @fractionDrop', 2), ('lea r8, [r8 + r8 * 4]', 4), ('lea r8, [rax + r8 * 2]', 4),
 ('@fractionNext:', 0), INC,
 ('@fractionLoad:', 0), LOAD, SUB, CMP9, ('jbe @fractionLoop', 2),
 # ---- after the digits (rcx = the terminator, al = terminator - 48): a dot is invalid, e/E starts the exponent
 ('@afterDigits:', 0), ('mov r10d, eax', 3), ('cmp al, 254', 2), ('je @nil', 2), ('or r10b, 32', 4), ('cmp r10b, 53', 4), ('jne @convert', 2),
 ('@exponent:', 0), INC, LOAD, ('cmp eax, 43', 3), ('je @exponentSign', 2), ('cmp eax, 45', 3), ('jne @exponentFirst', 2), ('or r11d, 4', 4),
 ('@exponentSign:', 0), INC, LOAD,
 ('@exponentFirst:', 0), SUB, CMP9, ('ja @nilExp', 2), ('xor r10d, r10d', 3), ('test eax, eax', 2), ('jnz @exponentLoop', 2),
 # ---- leading zeros of the exponent: at most 64 (r10 counts, then 0 again); beyond: nil
 ('@exponentZeros:', 0), INC, ('inc r10', 3), ('cmp r10, 64', 4), ('ja @nilExp', 2), LOAD, ('sub al, 48', 2), ('jz @exponentZeros', 2),
 ('xor r10d, r10d', 3), ('cmp al, 9', 2), ('jbe @exponentLoop', 2), ('jmp @exponentEnd', 2),
 ('@exponentLimit:', 0), ('mov rax, r10', 3), ('shl rax, 1', 3), ('jnz @nilExp', 2),
 ('test r11b, 4', 4), ('jz @nilExp', 2), ('jmp @exponentNext', 2),
 ('@scaleOverflow:', 0), ('test r8, r8', 3), ('jz @double', 2),
 ('@nilExp:', 0), ('xor eax, eax', 2), ('ret', 1),
 ('@exponentLoop:', 0), ('imul r10, r10, 10', 4), ('jo @nilExp', 2), ('add r10, rax', 3), ('jo @exponentLimit', 2),
 ('@exponentNext:', 0), INC, LOAD, SUB, CMP9, ('jbe @exponentLoop', 2),
 ('@exponentEnd:', 0), ('cmp al, 254', 2), ('je @nilExp', 2), ('mov rax, r10', 3), ('neg rax', 3), ('test r11b, 4', 4), ('cmovnz r10, rax', 4), ('add r9, r10', 3), ('jo @scaleOverflow', 2),
 # ---- convert: r8 = M (< 10^19), r9 = scale, r11 flags, rcx = the cursor; the type by value
 ('@convert:', 0), ('test r9, r9', 3), ('jnz @double', 2), ('mov r10d, 3', 6), ('test r11b, 8', 4), ('jnz @double', 2),
 ('cmp r8, 999999999', 7), ('jbe @typed', 2),
 ('mov eax, r11d', 3), ('and eax, 2', 3), ('shr eax, 1', 2), ('mov r10, 9223372036854775807', 10), ('add r10, rax', 3), ('cmp r8, r10', 3), ('ja @double', 2), ('mov r10d, 20', 6),
 ('@typed:', 0), ('test r11b, 2', 4), ('jnz @negateTyped', 2),
 ('mov qword ptr [rdx + 8], r8', 4), ('mov dword ptr [rdx], r10d', 3), ('mov rax, rcx', 3), ('ret', 1),
 ('@negateTyped:', 0), ('neg r8', 3), ('mov qword ptr [rdx + 8], r8', 4), ('mov dword ptr [rdx], r10d', 3), ('mov rax, rcx', 3), ('ret', 1),
 ('@zero:', 0), ('pxor xmm0, xmm0', 4), ('movsd qword ptr [rdx + 8], xmm0', 5), ('mov dword ptr [rdx], 5', 6), ('mov rax, rcx', 3), ('ret', 1),
 ('@double:', 0), ('test r11b, 1', 4), ('jz @nil', 2), ('test r8, r8', 3), ('jz @zero', 2), ('mov rax, r8', 3), ('test r9, r9', 3), ('jg @inexact', 2),
 ('shr rax, 53', 4), ('jnz @inexact', 2), ('lea rax, [r9 + 22]', 4), ('cmp rax, 44', 4), ('ja @inexact', 2),
 ('@exact:', 0), ('cvtsi2sd xmm0, r8', 5), ('lea rax, [rip + POW10]', 7), ('test r9, r9', 3), ('jns @exactMultiply', 2), ('neg r9', 3), ('divsd xmm0, [rax + r9 * 8 + 248]', 10),
 ('@done:', 0), ('test r11b, 2', 4), ('jnz @negateDone', 2), ('movsd qword ptr [rdx + 8], xmm0', 5), ('mov dword ptr [rdx], 5', 6), ('mov rax, rcx', 3), ('ret', 1),
 ('@exactMultiply:', 0), ('mulsd xmm0, [rax + r9 * 8 + 248]', 10), ('jmp @done', 2),
 # ---- inexact: strip the trailing decimal zeros, then the recoveries and the Pascal arithmetic (rcx kept)
 ('@inexact:', 0), ('mov rax, r8', 3), ('imul rax, [rip + INV5]', 8), ('ror rax, 1', 3), ('cmp rax, [rip + STRIPLIMIT]', 7), ('ja @stripped', 2), ('mov r10, rax', 3),
 ('@stripLoop:', 0), ('mov r8, rax', 3), ('inc r9', 3), ('mov rax, r8', 3), ('imul rax, [rip + INV5]', 8), ('ror rax, 1', 3), ('cmp rax, [rip + STRIPLIMIT]', 7), ('jbe @stripLoop', 2),
 ('@stripped:', 0), ('mov rax, r8', 3), ('shr rax, 53', 4), ('jnz @wideMantissa', 2), ('lea rax, [r9 + 22]', 4), ('cmp rax, 44', 4), ('jbe @exact', 2),
 ('test r9, r9', 3), ('jns @recover', 2),
 ('cvtsi2sd xmm0, r8', 5), ('lea rax, [rip + POW10]', 7), ('lea r10, [r9 + 31]', 4), ('cmp r10, 62', 4), ('ja @far', 2), ('mulsd xmm0, [rax + r10 * 8]', 6), ('jmp @done', 2),
 ('@recover:', 0), ('lea rax, [r9 - 23]', 4), ('cmp rax, 14', 4), ('ja @pascal', 2),
 ('cvtsi2sd xmm0, r8', 5), ('lea r10, [rip + POW10]', 7), ('movsd xmm1, [r10 + rax * 8 + 256]', 10), ('mulsd xmm1, xmm0', 4),
 ('comisd xmm1, [rip + EXACTINTEGER]', 8), ('ja @pascalScale', 2), ('mulsd xmm1, [r10 + 424]', 9), ('movapd xmm0, xmm1', 4), ('jmp @done', 2),
 ('@wideMantissa:', 0), ('lea rax, [r9 - 1]', 4), ('cmp rax, 2', 4), ('ja @pascal', 2), ('lea rax, [rip + POW10]', 7), ('cvttsd2si r10, [rax + r9 * 8 + 248]', 10),
 ('movq xmm2, rdx', 5), ('mov rax, r8', 3), ('mul r10', 3), ('mov r10, rdx', 3), ('movq rdx, xmm2', 5), ('test r10, r10', 3), ('jnz @pascal', 2), ('mov r8, rax', 3), ('xor r9d, r9d', 3),
 ('@pascal:', 0), ('test r8, r8', 3), ('js @pascalBig', 2), ('cvtsi2sd xmm0, r8', 5),
 ('@pascalScale:', 0), ('lea rax, [rip + POW10]', 7), ('lea r10, [r9 + 31]', 4), ('cmp r10, 62', 4), ('ja @far', 2), ('mulsd xmm0, [rax + r10 * 8]', 6), ('jmp @done', 2),
 ('@pascalBig:', 0), ('mov rax, r8', 3), ('shr rax, 1', 3), ('mov r10d, r8d', 3), ('and r10d, 1', 4), ('or rax, r10', 3), ('cvtsi2sd xmm0, rax', 5), ('addsd xmm0, xmm0', 4), ('jmp @pascalScale', 2),
 ('@far:', 0), ('lea r10, [r9 - 32]', 4), ('cmp r10, 256', 7), ('ja @farEdge', 2),
 ('mov r10d, r9d', 3), ('shr r10d, 5', 4), ('mov r8d, r9d', 3), ('and r8d, 31', 4), ('movsd xmm1, [rax + r10 * 8 + 520]', 10), ('mulsd xmm1, [rax + r8 * 8 + 248]', 10), ('mulsd xmm0, xmm1', 4), ('jmp @done', 2),
 ('@farEdge:', 0), ('test r9, r9', 3), ('jns @huge', 2),
 ('@wideNegative:', 0), ('mov r10d, r9d', 3), ('neg r10d', 3), ('cmp r9, -307', 7), ('jl @tiny', 2), ('mov r8d, r10d', 3), ('shr r10d, 5', 4), ('and r8d, 31', 4),
 ('movsd xmm1, [rax + r10 * 8 + 608]', 10), ('divsd xmm1, [rax + r8 * 8 + 248]', 10), ('mulsd xmm0, xmm1', 4), ('jmp @done', 2),
 ('@tiny:', 0), ('cmp r9, -342', 7), ('jl @nil', 2), ('lea r10d, [r9 + 342]', 7), ('cmp r9, -324', 7), ('jg @tinyScale', 2), ('cvttsd2si r10, [rax + r10 * 8 + 248]', 10),
 ('movq xmm2, rdx', 5), ('mov rax, [rip + UNDERFLOW]', 7), ('xor edx, edx', 2), ('div r10', 3), ('movq rdx, xmm2', 5), ('cmp r8, rax', 3), ('jbe @nil', 2), ('lea rax, [rip + POW10]', 7),
 ('@tinyScale:', 0), ('lea r8d, [r9 + 160]', 7), ('neg r8d', 3), ('mov r10d, r8d', 3), ('shr r8d, 5', 4), ('and r10d, 31', 4),
 ('movsd xmm1, [rax + r8 * 8 + 608]', 10), ('divsd xmm1, [rax + r10 * 8 + 248]', 10), ('mulsd xmm0, [rax + 648]', 8), ('mulsd xmm0, xmm1', 4), ('maxsd xmm0, [rip + MINBITS]', 8), ('jmp @done', 2),
 ('@huge:', 0), ('cmp r9, 308', 7), ('ja @nil', 2), ('lea r10d, [r9 - 289]', 7), ('je @lastPower', 2), ('cvttsd2si r10, [rax + r10 * 8 + 248]', 10),
 ('movq xmm2, rdx', 5), ('mov rax, [rip + OVERFLOW]', 7), ('xor edx, edx', 2), ('div r10', 3), ('movq rdx, xmm2', 5), ('cmp r8, rax', 3), ('ja @nil', 2), ('lea rax, [rip + POW10]', 7), ('jmp @hugeScale', 2),
 ('@lastPower:', 0), ('cmp r8, 1', 4), ('ja @nil', 2),
 ('@hugeScale:', 0), ('mov r10d, r9d', 3), ('shr r10d, 5', 4), ('mov r8d, r9d', 3), ('and r8d, 31', 4), ('movsd xmm1, [rax + r10 * 8 + 520]', 10), ('mulsd xmm1, [rax + r8 * 8 + 248]', 10),
 ('mulsd xmm1, [rip + INVSCALE]', 8), ('mulsd xmm0, xmm1', 4), ('minsd xmm0, [rip + MAXSCALED]', 8), ('mulsd xmm0, [rip + SCALE]', 8), ('jmp @done', 2),
 # ---- the capped phases that do not grow the mantissa (out of line): leading zeros of the fraction and
 # of the exponent, digits beyond the 19th; beyond 64 bytes the number is not accepted (nil)
 # ---- the negative double of the converter (out of the way: the rel8 reach of the convert jumps)
 ('@negateDone:', 0), ('pxor xmm1, xmm1', 4), ('cmpneqsd xmm1, xmm0', 5), ('andpd xmm1, [sign]', 8), ('xorpd xmm0, xmm1', 4), ('movsd qword ptr [rdx + 8], xmm0', 5), ('mov dword ptr [rdx], 5', 6), ('mov rax, rcx', 3), ('ret', 1),
]
LOOPS = {'@integerLoop': '@integerLoop', '@fractionLoop': '@fractionLoop', '@exponentLoop': '@exponentLoop', '@stripLoop': '@stripLoop',
         '@fractionZeros': '@fractionZeros', '@exponentZeros': '@exponentZeros', '@integerDropLoop': '@integerDropLoop', '@fractionDropLoop': '@fractionDropLoop'}
HARD_LOOPS = {'@fractionLoop', '@stripLoop'}
LOOP64 = 0
NOGAP = None
HOT = {'@unsigned', '@integerWideRows', '@fraction', '@storeDouble', '@fractionWideRows'}
WARM = {'@negateShort', '@integerShortExponent', '@negateWide', '@integerExponent', '@negateDouble', '@fractionShortExponent', '@fractionExponent',
        '@fastExponent', '@feSkip', '@feFirst', '@feEnd', '@fePlus', '@feDouble', '@feStore', '@feNegate', '@feDivide', '@feGeneric', '@feWide', '@negative',
        '@afterDigits', '@exponent', '@exponentSign', '@exponentFirst', '@exponentLoop', '@exponentNext', '@exponentEnd', '@nilExp',
        '@convert', '@typed', '@negateTyped', '@double', '@exact', '@done', '@negateDone', '@exactMultiply', '@zero', '@nil', '@nilHot'}
DEEP = {'@inexact'}
MEM = {
 '[sign]': '[rip + NumberSimdData + NUMBER_SIGN]', '[rip + NOSIMD]': 'dword ptr [rip + NumberNoSimd]',
 '[bias]': '[rip + NumberSimdData + NUMBER_BIAS]', '[threshold]': '[rip + NumberSimdData + NUMBER_THRESHOLD]',
 '[r8 + r10 * 8 + 576]': '[r8 + r10 * 8 + NUMBER_CTRLSHORT]', '[r8 + r10 * 8 + 96]': '[r8 + r10 * 8 + NUMBER_CTRLINT]',
 '[r8 + r9 * 8 + 336]': '[r8 + r9 * 8 + NUMBER_CTRLDOT]', '[r8 + r9 * 8 + 576]': '[r8 + r9 * 8 + NUMBER_CTRLSHORT]', '[r8 + r9 * 8 + 96]': '[r8 + r9 * 8 + NUMBER_CTRLINT]',
 '[r8 + 104]': 'qword ptr [r8 + NUMBER_E8]', '[r8 + r10 * 8 + 712]': 'qword ptr [r8 + r10 * 8 + NUMBER_POWERS - 8]',
 'cmp byte ptr [rcx], 45': "cmp byte ptr [rcx], '-'", 'cmp byte ptr [rcx], 48': "cmp byte ptr [rcx], '0'", 'cmp r9d, 46': "cmp r9d, '.'", 'cmp r9d, 101': "cmp r9d, 'e'",
 'cmp eax, 101': "cmp eax, 'e'", 'cmp eax, 46': "cmp eax, '.'", 'sub r9d, 12336': 'sub r9d, $3030',
 'mov dword ptr [rdx], 3': 'mov dword ptr [rdx], varInteger', 'mov dword ptr [rdx], 5': 'mov dword ptr [rdx], varDouble',
 'mov r10d, 3': 'mov r10d, varInteger', 'mov r9d, 20': 'mov r9d, varInt64', 'mov r10d, 20': 'mov r10d, varInt64',
 '[rip + INV5]': 'qword ptr [rip + NumberSimdData + NUMBER_INV5]', '[rip + STRIPLIMIT]': 'qword ptr [rip + NumberSimdData + NUMBER_STRIPLIMIT]',
 '[rip + EXACTINTEGER]': 'qword ptr [rip + NumberSimdData + NUMBER_EXACTINTEGER]',
 '[rip + UNDERFLOW]': 'qword ptr [rip + NumberSimdData + NUMBER_UNDERFLOW]',
 '[rip + OVERFLOW]': 'qword ptr [rip + NumberSimdData + NUMBER_OVERFLOW]',
 '[rip + INVSCALE]': 'qword ptr [rip + NumberSimdData + NUMBER_INVSCALE]',
 '[rip + MAXSCALED]': 'qword ptr [rip + NumberSimdData + NUMBER_MAXSCALED]',
 '[rip + SCALE]': 'qword ptr [rip + NumberSimdData + NUMBER_SCALE]',
 '[rip + MINBITS]': 'qword ptr [rip + NumberSimdData + NUMBER_MINBITS]',
 '[r8 + 32]': '[r8 + NUMBER_ASCII0]', '[r8 + 48]': '[r8 + NUMBER_TEN]', '[r8 + 64]': '[r8 + NUMBER_HUNDRED]',
 '[r8 + 80]': '[r8 + NUMBER_TENTHOUSAND]', '[r8 + 336]': '[r8 + NUMBER_CTRLINT + 15 * 16]',
 '[rax + r9 * 8 + 248]': 'qword ptr [rax + r9 * 8 + 31 * 8]',
 '[rax + r10 * 8 + 248]': 'qword ptr [rax + r10 * 8 + 31 * 8]',
 '[rax + r8 * 8 + 248]': 'qword ptr [rax + r8 * 8 + 31 * 8]',
 '[rax + r10 * 8 + 520]': 'qword ptr [rax + r10 * 8 + 65 * 8]',
 '[rax + r10 * 8 + 608]': 'qword ptr [rax + r10 * 8 + 76 * 8]',
 '[rax + r8 * 8 + 608]': 'qword ptr [rax + r8 * 8 + 76 * 8]',
 '[rax + 648]': 'qword ptr [rax + 81 * 8]',
 '[r10 + rax * 8 + 256]': 'qword ptr [r10 + rax * 8 + 32 * 8]',
 '[r10 + 424]': 'qword ptr [r10 + 53 * 8]',
 '[rax + r10 * 8]': 'qword ptr [rax + r10 * 8]',
}
COMMENT = {
 '@unsigned': (None, 'eax = P mod 4096 (after the sign), r8 = the table, r11 = AllowDouble | sign'),
 '@negateShort': ('        // ---- p integer digits (1..15), terminator at [rcx + p]: <= 8 digits, dword 0 = M; cursor rax ----', ''),
 '@integerShortExponent': (None, 'rax = the e, r8 = M'),
 '@integerWideRows': ('        // ---- 9 .. 15 digits right-aligned into lanes 1..15: M = H * 10^8 + L; the type by value --------', ''),
 '@negateWide': (None, ''),
 '@integerExponent': (None, 'rax = the e, r8 = M'),
 '@fraction': ('        // ---- p integer digits, the dot, fraction digits: eax = p, r10d = non-digit lanes -------', 'bit p of r10d is the dot'),
 '@storeDouble': (None, 'xmm0 = the value, rcx = the cursor; nil unless doubles are allowed; JSON zero is +0'),
 '@negateDouble': (None, 'the sign flipped unless the value is zero: JSON zero is +0 in every rounding mode'),
 '@fractionShortExponent': (None, 'scale = -f = 1 - (f + 1)'),
 '@fractionWideRows': (None, '9 .. 15 digits; n = 16 means the fraction runs past the window'),
 '@fractionExponent': (None, ''),
 '@fastExponent': ('        // ---- the inline exponent: xmm0 = the digits as an exact double, rcx = after the e, r9 = -f ---', 'up to 3 exponent digits (rcx + r8 = the current byte); the rest goes generic'),
 '@feSkip': (None, ''), '@feFirst': (None, 'the first exponent byte must be a digit'), '@feEnd': (None, 'eax = exponent (0..999), r10d = terminator - 48, rcx + r8 = the terminator'),
 '@fePlus': (None, ''), '@feDouble': (None, 'a nonzero scale: a double'), '@feStore': (None, ''), '@feNegate': (None, ''), '@feDivide': (None, 'scale -22 .. -1'),
 '@feGeneric': (None, '4+ exponent digits: the byte-loop exponent from the e (M as integer)'),
 '@feWide': (None, '|scale| > 22: the generic converter (canonical zeros, Pascal arithmetic, range)'),
 '@negative': ('        // ---- the minus sign, out of line: positive numbers fall through at the entry ------------', ''),
 '@windowFraction': ('        // ---- 15 digits with the dot at p, more fraction digits follow (eax = p) ----------------', 'the fraction runs past the window'),
 '@window0or16': ('        // ---- the window is full (16 digits): continue byte by byte from byte 16 -------------', 'eax = p: 0 = no leading digit (nil), 16 = full'),
 '@nil': ('        // ---- not a number: nil, Value untouched --------------------------------------------------', ''),
 '@nilHot': (None, 'not a number (a copy next to the hot paths: short jumps)'),
 '@bytes': ('        // ---- byte loops: the start without a window (page end), and every continuation ----------', 'rcx = first byte after an optional consumed -'),
 '@integerLoop': (None, 'rcx = the current digit (eax)'),
 '@integerNext': (None, ''),
 '@integerDone': (None, 'al = byte - 48; rcx = the terminator'),
 '@dot': (None, 'rcx = the dot: a digit must follow'),
 '@dot15': (None, 'scale 0, rcx = the dot'),
 '@fractionLoop': (None, 'rcx = the current fraction digit (eax); r9 = -f (counted before the drop test, undone there)'),
 '@fractionNext': (None, ''), '@fractionLoad': (None, ''),
 '@afterDigits': ('        // ---- after the digits: rcx = the terminator, al = terminator - 48 ------------------------', 'a dot after the number is invalid'),
 '@exponent': ('        // ---- exponent: rcx = the e, r8 = M, r9 = scale ----------------------------------------------', ''),
 '@exponentSign': (None, ''), '@exponentFirst': (None, 'at least one exponent digit'),
 '@exponentLoop': (None, 'r10 = the exponent value so far'), '@exponentNext': (None, ''),
 '@exponentEnd': (None, 'r10 = the exponent value; a dot after the exponent is invalid'),
 '@convert': ('        // ---- convert: r8 = M, r9 = scale, r11 flags, rcx = the cursor; the type by value -------------', 'an integer only with scale 0 and no dropped digit'),
 '@typed': (None, 'r10d = varInteger or varInt64, r8 = the magnitude'),
 '@negateTyped': (None, ''),
 '@double': (None, 'a double: nil unless allowed; a zero mantissa is +0 whatever the scale'),
 '@exact': (None, 'one exact operation: the nearest double'),
 '@done': (None, 'xmm0 = the value: store, the cursor, JSON zero is +0'),
 '@negateDone': (None, ''),
 '@exactMultiply': (None, 'scale 0 .. 22 (10^0 = 1 exactly)'),
 '@zero': (None, ''),
 '@inexact': ('        // ---- inexact: strip the trailing zeros ("1.50" = "1.5", "2745024e26" = "27450240000e22") --', ''),
 '@stripped': (None, 'canonical (M, scale): the same for every spelling of the value'),
 '@stripLoop': (None, 'M has trailing zeros: divide them out (M * inverse(5) ror 1 = M / 10 exactly); the mov before it keeps the loop off the jump pair'),
 '@recover': (None, 'scale 23 .. 37: exact while M * 10^(scale - 22) stays an integer below 2^53'),
 '@wideMantissa': (None, 'M >= 2^53: scale 1 .. 3 as one integer product when it fits 64 bits'),
 '@pascal': (None, 'the original Pascal arithmetic: M as a double, then the powers'),
 '@pascalScale': (None, ''),
 '@pascalBig': (None, 'M >= 2^63: halve with a sticky bit, convert, double'),
 '@far': (None, '|scale| > 31: the two POW10 constants of HugePower10Pos/Neg first'),
 '@farEdge': (None, ''), '@wideNegative': (None, ''),
 '@tiny': (None, 'scale <= -308: the decimal cutoff decides underflow exactly'),
 '@tinyScale': (None, '-324 < scale <= -308, or a nonzero result proved above'),
 '@huge': (None, 'scale 289 .. 308: the decimal cutoff decides overflow exactly'),
 '@lastPower': (None, '10^308: only M = 1 stays finite'),
 '@hugeScale': (None, ''),
 '@fractionZeros': (None, 'leading zeros of the fraction while M = 0: at most 64 (r9 counts them down)'),
 '@fractionZerosEnd': (None, 'the digit limit again (the window entry did not set it)'),
 '@exponentZeros': (None, 'leading zeros of the exponent: at most 64 (r10 counts, then 0 again)'),
 '@scaleOverflow': (None, 'the exponent fits; a zero mantissa survives combined-scale overflow'),
 '@nilExp': (None, 'not a number (a copy next to the exponent loop: short jumps)'),
 '@integerDrop': (None, 'an integer digit beyond the 19 kept: it raises the scale; the number is a double'),
 '@integerDropLoop': (None, ''),
 '@fractionDrop': (None, 'fraction digits beyond the 19 kept: skipped (the scale count of this one undone); the number is a double'),
 '@fractionDropLoop': (None, 'at most 64 dropped fraction digits (r10 counts down)'),
}
INS = {
 'or eax, [rip + NOSIMD]': '4096 on a CPU without SSSE3: the byte path then (the same contract)',
 'jz @nil': 'nil',
 'ja @bytes': 'the window would cross the page: byte loops from the start',
 'pcmpgtb xmm1, [threshold]': 'digit lanes',
 'not r10d': 'non-digit lanes; bits 16..31 are set',
 'bsf eax, r10d': 'p = leading digit count, 0..16',
 'ja @window0or16': 'p = 0: no leading digit; p = 16: the window is full',
 'movzx r9d, word ptr [rcx]': 'the first two bytes: "0" followed by a digit is not JSON',
 'ror r9d, 8': 'low byte 0 (a leading "0") and high byte 0..9 (a digit) <=> the value is 0..9',
 'jbe @nilHot': 'a leading zero',
 'movzx r9d, byte ptr [rcx + rax]': 'the byte after the integer digits',
 'ja @integerWideRows': '9 .. 15 digits',
 'lea r10d, [rax + rax]': 'row p (16 bytes each, scaled by 8 below)',
 'pshufb xmm0, [r8 + r10 * 8 + 576]': '<= 8 digits right-aligned into lanes 0..7: dword 0 is M',
 'movd r8d, xmm0': 'M',
 'add rax, rcx': 'the cursor: the terminator',
 'je @integerShortExponent': 'e/E: an exponent',
 'cmova r10d, r9d': 'ten or more significant digits: Int64',
 'pshufb xmm0, [r8 + r9 * 8 + 336]': 'the dot removed: all digits left-aligned, lane 15 zero',
 'btr r10d, eax': 'clear the dot',
 'bsf r10d, r10d': 'n = first non-digit after the fraction digits, p+1 .. 16',
 'lea r9d, [r10 + r10 - 2]': 'row n - 1',
 'sub r10d, eax': 'n - p = f + 1',
 'cmp r10d, 1': 'no digit after the dot',
 'add rcx, r10': 'the cursor: the byte after the fraction digits',
 'divsd xmm0, [r8 + r10 * 8 + 712]': '/ 10^f: M exact, 10^f exact, one rounding',
 'cmpneqsd xmm1, xmm0': 'all ones unless the value is zero', 'andpd xmm1, [sign]': 'the sign bit, or nothing for a zero', 'xorpd xmm0, xmm1': 'JSON zero stays +0 in every rounding mode',
 'jz @fractionZeros': 'a zero window mantissa: the continuation zeros are leading zeros',
 'je @dot15': 'the dot is the last window byte: a digit must follow it',
 'mov r10, 1000000000000000000': '10^18: 19 significant digits kept',
 'lea r9, [rax - 15]': 'scale = -(15 - p), 64-bit (a negative value)',
 'add rcx, 15': 'the last window byte: the loops advance before they load',
 'cmp byte ptr [rcx], 48': '16 digits starting with a zero: not JSON',
 'jae @integerDrop': '19 significant digits kept: this one raises the scale',
 'jae @fractionDrop': '19 significant digits kept: this one is dropped',
 'cmp al, 254': "'.'",
 'cmp r10b, 53': "'e' or 'E' (bit 5 set by the OR)",
 'jo @nilExp': 'an exponent beyond 64 bits, or a scale beyond 64 bits: not a number',
 'cmovnz r10, rax': 'a negative exponent',
 'jnz @feDouble': 'a nonzero scale: a double; scale 0: an integer of the digits',
 'cvttsd2si r8, xmm0': 'M (exact: below 10^15)',
 'cmp r10d, -2': 'a dot after the exponent',
 'jg @inexact': 'a positive scale: strip the zeros first, then choose (spellings agree)',
 'shr rax, 53': 'M >= 2^53: not exact',
 'cmp rax, 44': '|scale| <= 22',
 'mulsd xmm0, [rax + r9 * 8 + 248]': '* 10^scale (10^0 = 1 exactly)',
 'ror rax, 1': 'M * inverse(5) ror 1 = M / 10 when M is divisible by 10',
 'ja @stripped': 'not divisible by 10 (the common M): nothing to strip',
 'jns @recover': 'a positive scale: the 23..37 recovery, else the Pascal product',
 'cmp rax, 14': 'scale 23 .. 37: exact while M * 10^(scale - 22) stays an integer below 2^53',
 'ja @pascalScale': 'not an exact integer: the Pascal product',
 'mulsd xmm1, [r10 + 424]': '* 10^22, exact: one rounding in all',
 'cvttsd2si r10, [rax + r9 * 8 + 248]': '10^scale as an integer',
 'movq xmm2, rdx': 'MUL/DIV need rdx: the Value pointer waits in xmm2',
 'jnz @pascal': 'the product does not fit: the Pascal path',
 'mulsd xmm0, [rax + r10 * 8]': '* POW10[scale], |scale| <= 31',
 'cmp r10, 256': 'scale 32 .. 288',
 'movsd xmm1, [rax + r10 * 8 + 520]': 'POW10[34 + hi] = 10^(32 * hi)',
 'mulsd xmm1, [rax + r8 * 8 + 248]': '* 10^lo (HugePower10Pos)',
 'movsd xmm1, [rax + r10 * 8 + 608]': 'POW10[45 + hi] = 10^-(32 * hi)',
 'movsd xmm1, [rax + r8 * 8 + 608]': 'POW10[45 + hi] = 10^-(32 * hi)',
 'divsd xmm1, [rax + r8 * 8 + 248]': '/ 10^lo (HugePower10Neg)',
 'divsd xmm1, [rax + r10 * 8 + 248]': '/ 10^lo (HugePower10Neg)',
 'div r10': 'floor(cutoff midpoint / 10^n)',
 'mulsd xmm0, [rax + 648]': '* 10^-160 (POW10[50]): a normal intermediate',
 'maxsd xmm0, [rip + MINBITS]': 'the cutoff proved a nonzero result',
 'mulsd xmm1, [rip + INVSCALE]': '10^scale * 2^-512',
 'minsd xmm0, [rip + MAXSCALED]': 'the cutoff proved a finite result',
 'ja @nil': 'not a number',
 'jl @nil': 'below the smallest subnormal: not a number',
}
FILE = Path(__file__).resolve().parents[1] / 'mormot.core.variants.asmx64.number.inc'
FUNC = 'function GetNumericVariantFromJson(Json: PUtf8Char; var Value: TVarData; AllowVarDouble: boolean): PUtf8Char;'
