"""The string routine (GetExtended) as a routine module for the generic tools: the sheet lives in
plan_hot.py + plan_cold.py; this module supplies layout policy and operand/comment mappings."""
from pathlib import Path
import plan_hot, plan_cold
NAME = 'string'
hot = plan_hot.hot
cold = plan_cold.cold
LOOPS = plan_cold.LOOPS
HARD_LOOPS = {'@fractionLoop', '@stripLoop'}   # Other loops are placement preferences, reported by the checker.
# pad weights by region: the hot NUL paths (10: a prefix there only when no gap can do it), the
# quote/exponent endings and the exponent/convert path (3), the byte loops (1), the rare converter (0.5)
HOT = {'@unsigned', '@integerShortTail', '@integerWideRows', '@integerWide', '@fraction', '@fractionShortValue', '@fractionWideRows', '@fractionValue'}
WARM = {'@negateIntegerShort', '@integerShortEnded', '@integerShortExponent', '@negateInteger', '@integerEnded', '@integerExponent',
        '@negateFraction', '@fractionShortEnded', '@fractionShortExponent', '@fractionEnded', '@fractionExponent', '@negative',
        '@fastExponent', '@feSkip', '@feFirst', '@feEnd', '@fePlus', '@feMultiply', '@feGeneric', '@feWide',
        '@afterDigits', '@exponent', '@exponentSign', '@exponentFirst', '@exponentLoop', '@terminator', '@convert', '@exact', '@done', '@exactMultiply', '@negate'}
DEEP = {'@inexact'}   # from here on: the rare converter paths
LOOP64 = 0
NOGAP = ('@afterDigits', '@inexact')   # no gaps between these labels (rel8 jumps must stay short)
MEM = {
 '[sign]': '[rip + NumberSimdData + NUMBER_SIGN]', '[rip + NOSIMD]': 'dword ptr [rip + NumberNoSimd]',
 '[bias]': '[rip + NumberSimdData + NUMBER_BIAS]', '[threshold]': '[rip + NumberSimdData + NUMBER_THRESHOLD]',
 '[r8 + rax + 576]': '[r8 + rax + NUMBER_CTRLSHORT]', '[r8 + rax + 96]': '[r8 + rax + NUMBER_CTRLINT]', '[r8 + rax + 336]': '[r8 + rax + NUMBER_CTRLDOT]',
 '[r8 + r10 + 560]': '[r8 + r10 + NUMBER_CTRLSHORT - 16]', '[r8 + r10 + 80]': '[r8 + r10 + NUMBER_CTRLINT - 16]',
 '[r8 + 104]': 'qword ptr [r8 + NUMBER_E8]', '[r8 + r10 + 712]': 'qword ptr [r8 + r10 + NUMBER_POWERS - 8]',
 'cmp byte ptr [rcx], 45': "cmp byte ptr [rcx], '-'", 'cmp r9d, 46': "cmp r9d, '.'", 'cmp r9d, 101': "cmp r9d, 'e'",
 '[rip + EXACTINTEGER]': 'qword ptr [rip + NumberSimdData + NUMBER_EXACTINTEGER]',
 '[rip + UNDERFLOW]': 'qword ptr [rip + NumberSimdData + NUMBER_UNDERFLOW]',
 '[rip + OVERFLOW]': 'qword ptr [rip + NumberSimdData + NUMBER_OVERFLOW]',
 '[rip + INVSCALE]': 'qword ptr [rip + NumberSimdData + NUMBER_INVSCALE]',
 '[rip + MAXSCALED]': 'qword ptr [rip + NumberSimdData + NUMBER_MAXSCALED]',
 '[rip + SCALE]': 'qword ptr [rip + NumberSimdData + NUMBER_SCALE]',
 '[rip + MINBITS]': 'qword ptr [rip + NumberSimdData + NUMBER_MINBITS]',
 '[r8 + 32]': '[r8 + NUMBER_ASCII0]', '[r8 + 48]': '[r8 + NUMBER_TEN]', '[r8 + 64]': '[r8 + NUMBER_HUNDRED]',
 '[r8 + 80]': '[r8 + NUMBER_TENTHOUSAND]', '[r8 + 336]': '[r8 + NUMBER_CTRLINT + 15 * 16]',
 '[rax + r9 * 8 + 248]': 'qword ptr [rax + r9 * 8 + 31 * 8]',
 '[rax + rcx * 8 + 248]': 'qword ptr [rax + rcx * 8 + 31 * 8]',
 '[rax + r10 * 8 + 248]': 'qword ptr [rax + r10 * 8 + 31 * 8]',
 '[rax + rcx * 8 + 520]': 'qword ptr [rax + rcx * 8 + 65 * 8]',
 '[rax + rcx * 8 + 608]': 'qword ptr [rax + rcx * 8 + 76 * 8]',
 '[rax + 648]': 'qword ptr [rax + 81 * 8]',
 '[rcx + rax * 8 + 256]': 'qword ptr [rcx + rax * 8 + 32 * 8]',
 '[rcx + 424]': 'qword ptr [rcx + 53 * 8]',
 '[rax + rcx * 8]': 'qword ptr [rax + rcx * 8]',
}
COMMENT = {  # per label: the block comment (before the label) and the label comment
 '@unsigned': (None, 'eax = P mod 4096 (after the sign), err = 0 stored'),
 '@integerShortTail': ('        // ---- p integer digits (1..15), terminator at [rcx + p]: <= 8 digits, dword 0 = M ---------', ''),
 '@negateIntegerShort': (None, ''),
 '@integerShortEnded': (None, 'another byte after <= 8 digits: an exponent, or the integer so far with err = 1'),
 '@integerShortExponent': (None, 'rcx = after the e, M in r8, scale 0'),
 '@integerWideRows': ('        // ---- 9 .. 15 digits right-aligned into lanes 1..15: M = H * 10^8 + L ----------------', ''),
 '@integerWide': (None, ''),
 '@negateInteger': (None, ''),
 '@integerEnded': (None, 'another byte after 9 .. 15 digits'),
 '@integerExponent': (None, ''),
 '@fraction': ('        // ---- p integer digits, the dot, fraction digits: eax = p, r10d = non-digit lanes -------', 'bit p of r10d is the dot'),
 '@fractionShortValue': (None, 'M / 10^f: both exact, one rounding'),
 '@negateFraction': (None, ''),
 '@fractionShortEnded': (None, 'another byte after <= 8 fraction digits'),
 '@fractionShortExponent': (None, 'scale = -f'),
 '@fractionWideRows': (None, '9 .. 15 digits; n = 16 means the fraction runs past the window'),
 '@fractionValue': (None, 'M exact, 10^f exact, one rounding'),
 '@fractionEnded': (None, 'another byte after 9 .. 15 fraction digits'),
 '@fractionExponent': (None, ''),
 '@fastExponent': ('        // ---- the inline exponent: xmm0 = the digits as an exact double, rcx = after the e, r9 = -f ---', 'up to 3 exponent digits; |scale| <= 22 converted here, the rest goes generic'),
 '@feSkip': (None, ''), '@feFirst': (None, ''), '@feEnd': (None, 'eax = exponent (0..999), r10d = terminator - 48'), '@fePlus': (None, ''),
 '@feMultiply': (None, 'scale 0 .. 22'), '@feGeneric': (None, 'no exponent digit or 4+ digits: the byte-loop exponent from after the e (M as integer)'),
 '@feWide': (None, '|scale| > 22: the generic converter (canonical zeros, Pascal arithmetic, range)'),
 '@negative': ('        // ---- the minus sign, out of line: positive numbers fall through at the entry ------------', ''),
 '@integerDone1': (None, ''),
 '@integerMaybeZero': ('        // ---- the capped phases that do not grow the mantissa: leading zeros of the integer, the fraction, the exponent; beyond 64 bytes the text ends like garbage (err = 1) ----', 'M = 0 so far: a zero digit starts the zero-skip'),
 '@fractionMaybeZero': (None, 'M = 0 so far'),
 '@integerZeros': (None, 'leading zeros of the integer while M = 0: at most 64 (r8 counts, then M = 0 again)'),
 '@fractionZeros': (None, 'leading zeros of the fraction while M = 0: at most 64 (r9 counts them down)'),
 '@fractionZerosEnd': (None, ''),
 '@exponentZeros': (None, 'leading zeros of the exponent: at most 64 (r10 counts, then 0 again)'),
 '@exponentNext': (None, ''),
 '@exponentBig': (None, 'an exponent of 10^9 or more: the remaining digits (at most 64) are skipped, the scale stays huge - the converter gives 0 for M = 0 and a range error otherwise'),
 '@exponentBigLoop': (None, ''),
 '@exponentEnd': (None, 'r10 = the exponent value'),
 '@fractionDropLoop': (None, 'at most 64 dropped fraction digits (r10 counts down)'),
 '@garbageZero': ('        // ---- beyond a cap: the text ends here like a garbage terminator: err = 1, the value so far ----', 'a zero mantissa (spaces or leading zeros): M = 0'),
 '@garbageInt': (None, 'a dropped-digit run beyond the cap: M kept'),
 '@garbageExp': (None, ''),
 '@fractionExit': (None, 'the trailing zeros of the fraction are dropped (canonical M); flags and err pointer back'),
 '@fractionDrop': (None, 'fraction digits beyond the 19 kept: skipped, one taken jump per digit'),
 '@exactMultiply': (None, 'scale 0 .. 22 (10^0 = 1 exactly)'),
 '@stripLoop': (None, 'M has trailing zeros: divide them out (M * inverse(5) ror 1 = M / 10 exactly)'),
 '@recover': (None, 'scale 23 .. 37: exact while M * 10^(scale - 22) stays an integer below 2^53'),
 '@windowFraction': ('        // ---- 15 digits with the dot at p, more fraction digits follow (eax = p * 16) -----------', 'the fraction runs past the window'),
 '@window0or16': ('        // ---- the window is full (16 digits): continue byte by byte from byte 16 -------------', 'eax = p: 0 = no leading digit, 16 = full'),
 '@nil': (None, 'a nil text: 0 with err = 1'),
 '@integerDrop': (None, 'an integer digit beyond the 19 kept: it raises the scale'),
 '@bytes': ('        // ---- byte loops: the start without a window, and every continuation ------------------', 'rcx = first byte after an optional consumed -'),
 '@plusSign': (None, ''),
 '@integerFirst': (None, 'the first byte decides whether a digit was seen at all'),
 '@integerLoop': (None, 'rcx = a digit'),
 '@integerDone': (None, 'al = byte - 48; rcx moves past the byte'),
 '@fractionLoop': (None, 'rcx = the byte after a digit; r11/rdx = (M, scale) after the last nonzero digit'),
 '@fractionNext': (None, ''),
 '@afterDigits': ('        // ---- after the digits: rcx = past the terminator, al = terminator - 48 ----------------', ''),
 '@exponent': ('        // ---- exponent: rcx = after \'e\', r8 = M, r9 = scale ---------------------------------', ''),
 '@exponentLoop': (None, 'r10 = the exponent value so far'),
 '@terminator': (None, 'err = 0 for NUL after a digit'),
 '@convert': ('        // ---- convert: r8 = M, r9 = scale, r10d = err, r11 bit 0 = sign -----------------------', ''),
 '@exact': (None, 'one exact operation: the nearest double'),
 '@done': (None, ''),
 '@inexact': ('        // ---- inexact: strip the trailing zeros ("1.50" = "1.5", "2745024e26" = "27450240000e22") --', ''),
 '@stripped': (None, 'canonical (M, scale): the same for every spelling of the value'),
 '@wideMantissa': (None, 'M >= 2^53: scale 1 .. 3 as one integer product when it fits 64 bits'),
 '@pascal': (None, 'the original Pascal arithmetic: M as a double, then the powers'),
 '@pascalBig': (None, 'M >= 2^63: halve with a sticky bit, convert, double'),
 '@far': (None, '|scale| > 31: the two POW10 constants of HugePower10Pos/Neg first'),
 '@tiny': (None, 'scale <= -308: the decimal cutoff decides underflow exactly'),
 '@tinyScale': (None, '-324 < scale <= -308, or a nonzero result proved above'),
 '@huge': (None, 'scale 289 .. 308: the decimal cutoff decides overflow exactly'),
 '@lastPower': (None, '10^308: only M = 1 stays finite'),
 '@range': (None, 'err = 1, the value is the stripped mantissa as an integer (the same on every path)'),
 '@scaleOverflow': (None, 'the exponent fits; a zero mantissa survives combined-scale overflow'),
 '@windowZeros': (None, 'the full SIMD window consumed 16 leading zeroes already'),
 '@rangeM': (None, 'from the exponent loop: r8 = M, not yet stripped'),
 '@rangeStrip': (None, ''),
 '@exponentNone': (None, '"1e", "1e+", "1ex": err 1, the value without an exponent'),
}
INS = {  # per instruction text: a trailing comment
 'jz @zero': 'a zero mantissa with an absurd exponent: 0 with err = 1',
 'or eax, [rip + NOSIMD]': '4096 on a CPU without SSSE3: the byte path then (the same contract)',
 'jz @bytes': 'no leading digit: spaces, \'+\', \'.\', letters',
 'ja @bytes': 'the window would cross the page: byte loops from the start',
 'ja @garbageInt': 'more than 64 bytes in this phase: garbage',
 'ja @garbageZero': 'more than 64 bytes in this phase: garbage',
 'ja @garbageExp': 'more than 64 bytes in this phase: garbage',
 'jz @fractionZeros': 'a zero window mantissa: the continuation zeros are leading zeros',
 'mov dword ptr [rdx], 0': 'err for a NUL terminator; the other endings rewrite it',
 'pcmpgtb xmm1, [threshold]': 'digit lanes',
 'not r10d': 'non-digit lanes; bits 16..31 are set',
 'bsf eax, r10d': 'p = leading digit count, 0..16',
 'ja @window0or16': 'p = 0: no leading digit; p = 16: the window is full',
 'movzx r9d, byte ptr [rcx + rax]': 'the byte after the integer digits',
 'ja @integerWideRows': '9 .. 15 digits',
 'pshufb xmm0, [r8 + rax + 576]': '<= 8 digits right-aligned into lanes 0..7: dword 0 is M',
 'pshufb xmm0, [r8 + rax + 336]': 'the dot removed: all digits left-aligned, lane 15 zero',
 'btr r10d, eax': 'clear the dot',
 'bsf r10d, r10d': 'n = first non-digit after the fraction digits, p+1 .. 16',
 'shr r10d, 1': '(n - p) * 8 = (f + 1) * 8',
 'jns @feMultiply': 'a negative scale falls through to the exact division',
 'ja @feWide': '|scale| > 22',
 'jns @exactMultiply': 'a negative scale (the exponent class) falls through to the exact division',
 'jbe @stripLoop': 'divisible by 10: strip the zeros out of line (the common M has none)',
 'jns @recover': 'a positive scale: the 23..37 recovery, else the Pascal product',
 'mov r10, 1000000000000000000': '10^18: 19 significant digits kept',
 'lea r9, [rax - 15]': 'scale = -(15 - p), 64-bit (a negative value)',
 'jae @integerDrop': '19 significant digits kept: this one raises the scale',
 'jae @fractionNext': '19 significant digits kept: this one is dropped',
 'cmp al, 254': '\'.\'',
 'cmp r10b, 53': '\'e\' or \'E\' (bit 5 set by the OR)',
 'jo @rangeM': 'the exponent value exceeds signed 64-bit magnitude',
 'cmovnz r10, rcx': 'a negative exponent',
 'cmovnz r11, r8': 'a nonzero digit: the checkpoint moves here',
 'mov r8, r11': 'the trailing zeros of the fraction are dropped (canonical M)',
 'movq xmm3, rdx': 'the err pointer and the flags wait in xmm3/xmm4 during the loop',
 'cmp al, 208': 'NUL',
 'jg @inexact': 'a positive scale: strip the zeros first, then choose (spellings agree)',
 'shr rax, 53': 'M >= 2^53: not exact',
 'cmp rax, 44': '|scale| <= 22',
 'mulsd xmm0, [rax + r9 * 8 + 248]': '* 10^scale (10^0 = 1 exactly)',
 'ror rax, 1': 'M * inverse(5) ror 1 = M / 10 when M is divisible by 10',
 'cmp rax, 14': 'scale 23 .. 37: exact while M * 10^(scale - 22) stays an integer below 2^53',
 'ja @pascalScale': 'not an exact integer: the Pascal product',
 'mulsd xmm1, [rcx + 424]': '* 10^22, exact: one rounding in all',
 'cvttsd2si rcx, [rax + r9 * 8 + 248]': '10^scale as an integer',
 'mov r10, rdx': 'MUL needs rdx: keep the err pointer in r10',
 'jnz @pascal': 'the product does not fit: the Pascal path',
 'mulsd xmm0, [rax + rcx * 8]': '* POW10[scale], |scale| <= 31',
 'cmp rax, 256': 'scale 32 .. 288',
 'movsd xmm1, [rax + rcx * 8 + 520]': 'POW10[34 + hi] = 10^(32 * hi)',
 'mulsd xmm1, [rax + r10 * 8 + 248]': '* 10^lo (HugePower10Pos)',
 'movsd xmm1, [rax + rcx * 8 + 608]': 'POW10[45 + hi] = 10^-(32 * hi)',
 'divsd xmm1, [rax + r10 * 8 + 248]': '/ 10^lo (HugePower10Neg)',
 'div r10': 'floor(cutoff midpoint / 10^n)',
 'mov rcx, rdx': 'DIV needs rdx: keep the err pointer in rcx',
 'jbe @range': 'rounds to zero',
 'mulsd xmm0, [rax + 648]': '* 10^-160 (POW10[50]): a normal intermediate',
 'maxsd xmm0, [rip + MINBITS]': 'the cutoff proved a nonzero result',
 'mulsd xmm1, [rip + INVSCALE]': '10^scale * 2^-512',
 'minsd xmm0, [rip + MAXSCALED]': 'the cutoff proved a finite result',
}

FILE = Path(__file__).resolve().parents[1] / 'mormot.core.base.asmx64.number.string.inc'
FUNC = 'function GetExtended(P: PUtf8Char; out err: integer): TSynExtended;'
